public class AnimalLocator{
    public static String getAnimalNameById(Integer x){

        Http h = new Http();

        HttpRequest req = new HttpRequest();
        req.setEndpoint('https://th-apex-http-callout.herokuapp.com/animals/' + x);
        req.setMethod('GET');

        HttpResponse res = h.send(req);

        Map<String, Object> results = (Map<String, Object>)JSON.deserializeUntyped(res.getBody());
        Map<String, Object> animal = (Map<String, Object>) results.get('animal');

        return (String)animal.get('name');
    }
}