@isTest
Public class checkRecursive_trgrecursive_Test{
    Public static testMethod Void checkRecursive_trgrecursive_Test(){
        checkRecursive_trgrecursive.runOnce();
    
    }
    Public static testMethod Void checkRecursive_trgrecursivebefore_Test(){
        checkRecursive_trgrecursive.beforerunOnce();
    
    }
    Public static testMethod Void checkRecursive_trgrecursiveafter_Test(){
        checkRecursive_trgrecursive.afterrunOnce();
    
    }

}