public with sharing class csaClaimSystemConstants {
    public static final String BLANK = '';
    public static final String COMMA_SPACE = ', ';
    public static final String PROPERTY_CATEGORY = 'csa Claiming System';
    public static final String PROPERTY_INSTALLEDKEY = 'nCino_Claiming_System';
    public static final String PROPERTY_INSTALLEDVALUE = 'true';
    public static final String PROPERTY_LOANKEY = 'Claim_Loan_Field_Set';
    public static final String PROPERTY_PRODUCTPACKAGEKEY = 'Claim_Product_Package_Field_Set';
    public static final String PROPERTY_LOANVALUE = 'CSA_LoanClaimFields';
    public static final String PROPERTY_PRODUCTPACKAGEVALUE = 'CSA_ProductPackageClaimFields';
}