/****************************************************************************************
Name            : IConfigStep
Revision Log    : 2020-02-27 John Kuhl - CodeScience
                :
                :
Use             : Interface for Config Step Classes
****************************************************************************************/
public Interface IConfigStep {
    /**
     * execute
     *
     * This method executes the the configuration step
     **/
    void execute();
    
}