/*
*******************************************************************************************
* Name          IntegrationTokenDetails
* Author        Deepak Kumar Reddy Regatte
* ModifiedBy    Deepak Kumar Reddy Regatte
* CreatedDate   02/24/2020
* UsedBy        The IntegrationTokenDetails is a wrapper class for IntegrationUtility.
* Description Jira user story PRCDM2-1904
*********************************************************************************************
*/
public class IntegrationTokenDetails  {
    public String issued_at{get;set;}
    public String application_name{get;set;}
    public String status{get;set;}
    public String expires_in{get;set;}
    public String client_id{get;set;}    
    public String access_token{get;set;}
    public Datetime currentTime{get;set;}
    public Boolean isNewToken{get;set;}      
  
}