/**
/** Author       ::: Ranjith Kumar
/** User Story   ::: PRDCRM-49344
/** Team Name    ::: Vikings
/** Purpose      ::: This is used for to store all Team Roles.
/** Version      ::: v1.0
/** Created Date ::: 28-Jan-2020
**/

public class StaticVariablesforOppTeamRoles{
    public static String AccountManager='Account Manager';
    public static String AccountExecutive='Account Executive';
    public static String SpecialtySalesAccountManager='Specialty Sales Account Manager';
    public static String SpecialtySalesExecutive='Specialty Sales Executive';
    public static String SpecialtySalesSupport='Specialty Sales Support';
    public static String SpecialtyClinicalAccountDirector='Specialty Clinical Account Director';
    public static String GRSSalesSupport='GRS Sales Support';
    public static String GRSAccountManager='GRS Account Manager';
    public static String GRSUnderwriter='GRS Underwriter';
    public static String GRSAdministrator='GRS Administrator';
    public static String VP='VP';
    public static String SalesAccountRepresentative='Sales Account Representative';
    public static String Underwriter='Underwriter';
    public static String AccountServiceRepresentative='Account Service Representative';
    public static String DirectorSalesAM='Director Sales/AM';
    public static String GRSAccountExecutive='GRS Account Executive';
    public static String GRSESR='GRS ESR';
    public static String SalesAccountRepAcctMgmt='Sales Account Rep - Acct Mgmt';
    public static String VoluntaryEnrollmentConsultant='Voluntary Enrollment Consultant';
}