vlocity_ins__Code__c,Name,vlocity_ins__DisplaySequence__c,vlocity_ins__UIControlType__c,vlocity_ins__IsActive__c,vlocity_ins__ApplicableTypes__c,vlocity_ins__ApplicableSubType__c,vlocity_ins__IsPrivate__c,vlocity_ins__IsUserAttributesCreatedPrivate__c
inn,In Network,1000,On-Off,TRUE,Product2,Product Attribute,TRUE,TRUE
innl2,In Network Lvl2,1005,On-Off,TRUE,Product2,Product Attribute,TRUE,TRUE
oon,Out of Network,1010,On-Off,TRUE,Product2,Product Attribute,TRUE,TRUE
SCP,Specialty Care Provider,1015,On-Off,TRUE,Product2,Product Attribute,TRUE,TRUE
PCP,Primary Care Provider,1020,On-Off,TRUE,Product2,Product Attribute,TRUE,TRUE
EMRM,Emergency Room,1025,On-Off,TRUE,Product2,Product Attribute,TRUE,TRUE
UCARE,Urgent Care,1030,On-Off,TRUE,Product2,Product Attribute,TRUE,TRUE
RXPLAN,Pharmacy Plan,1035,On-Off,TRUE,Product2,Product Attribute,TRUE,TRUE
VISON,Vision Plan,1040,On-Off,TRUE,Product2,Product Attribute,TRUE,TRUE
OTHER,Other Plan Details,1100,On-Off,TRUE,Product2,Product Attribute,TRUE,TRUE
VISION_OON,Vision Out of Network,2010,On-Off,TRUE,Product2,Product Attribute,TRUE,TRUE
VISION_OTHER,Vision Other Plan Details,2100,On-Off,TRUE,Product2,Product Attribute,TRUE,TRUE
VISION_frequency,Vision Plan Frequencies,2000,On-Off,TRUE,Product2,Product Attribute,TRUE,TRUE
VISION_INN,Vision In Network,2005,On-Off,TRUE,Product2,Product Attribute,TRUE,TRUE
